
platform :ios, '13.0'
workspace 'Sprout'

target 'Sprout' do
  use_frameworks!
  
  # Pods for Sprout
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
  # For loading
  pod 'GradientLoadingBar' , '~> 2.0'
  
  #Dealing with JSON Files
  pod 'SwiftyJSON', '~>4.0'

end
